### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by smoliji** [AckeeCZ/cosmas#24] opened 2019-11-04 14:13 UTC
I have noticed that adding cosmas logger to the project and using it to log errors via `cosmas.error` slows down the app drastically - app avg response time for 450 requests and 130 logs raised from tens of ms to above one sec.

Compared to native `console` logging.

Havent done any tests or comparisons against underlying pino directly. I'd be interested in seeing the performance impact of cosmas, if there is any.

**Comment by vlasy** [comment] 2019-11-05 14:40
Can you provide cosmas version and logger settings?

**Comment by smoliji** [comment] 2019-11-05 16:33
Sure.
`"cosmas": "^1.0.3"`
And the defaults, just like that
```js
import logger from 'cosmas';
// ...
logger.error({ error }, 'msg')
```

Dunno if it helps, but the `error` is an error from `googleapis` lib, call `google.people('v1').people.get`

**Comment by vlasy** [comment] 2019-11-06 12:08
I am unable to reproduce the issue you are having. We will add performance comparison in the future - #26 

Closing for now

**Closed by vlasy** 2019-11-06 12:08 UTC
